sudo: required
services:
  - docker

before_install:
  docker build -t shiqi -f Dockerfile.dev .


script:
  - docker run -e CI=true shiqi npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-453804884769"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
